Repository openHPI/quiz-recap, pull requests merged in 2024-04, with the labels that each got.

#40 Add new GitHub Actions workflow for CI
  .github/workflows/ci.yml
  .github/workflows/node.yml
Labels: maintenance 🛠️, show 👀

#39 [XI-6321] Add multiple attempts feature
  README.md
  src/App.test.tsx
  src/App.tsx
  src/components/Answers.test.tsx
  src/components/Answers.tsx
  src/components/Form.tsx
  src/components/Quiz.test.tsx
  src/components/Quiz.tsx
  src/components/Result.module.scss
  src/components/Result.tsx
  src/locales/de.ts
  src/locales/en.ts
  src/static/data.ts
  src/types.ts
Labels: enhancement

#62 Fix hint in answer breaking markdown content
  src/components/Answers.module.scss
  src/components/Answers.tsx
  src/locales/de.ts
  src/locales/en.ts
  src/static/data.ts
Labels: bug

#61 XI-6316 Add referenceLink to question object
  src/App.test.tsx
  src/components/Result.test.tsx
  src/components/Result.tsx
  src/locales/de.ts
  src/locales/en.ts
  src/static/data.ts
  src/types.ts
Labels: enhancement

#68 Run type check in pre-commit hook
  .husky/pre-commit
Labels: maintenance 🛠️, show 👀

#71 Display remaining attempts after submitting a wrong answer
  src/App.test.tsx
  src/components/Form.tsx
  src/components/Question.tsx
  src/locales/de.ts
  src/locales/en.ts
Labels: enhancement

#79 Run tests pre-push instead of pre-commit
  .husky/pre-commit
  .husky/pre-push
Labels: maintenance 🛠️, show 👀
